### ISSUE TITLE
Missing DM_ENV

### ISSUE THREAD

**Issue by macasas** [dev-mastery/comments-api#11]
Hi, the sampledotenv doesn't contain a DM_ENV, 

Before the build the index.js code looks like this:
if (process.env.DM_ENV === 'dev') {

After build, the code looks like this:
if ((process && process.env && process.env.DM_ENV || "dev") === 'dev') {
which I think should equate to "dev" === 'dev' but somehow doesn't.

so index.js never starts listening:
app.listen(3000, () => {

until I add DM_ENV=dev to my .env file.

Which is kind of fundamental to you all running this code so are you all just adding DM_ENV and then not mentioning it because it's so obvious, or is something else going on that I just cannot see?

**Comment by arcdev1** [comment]
This is artefact of the way ZEIT's deployments used to work. It should probably be removed because it will add more confusion than necessary.  I'd gladly take a pull request.

**Comment by macasas** [comment]
My node server still uses this dotenv method so I thought it was common practice :-)

Sorry, git pull requests are still on the training list. I understand git commit, but as soon as I go away from any tutorial I get git error messages, and that's not just you, that's for everyone. Git makes my head hurt, so it keeps getting pushed down the list, its the only way to stay sane!

**Comment by arcdev1** [comment]
No worries!

**Comment by arcdev1** [comment]
Using environment variables is indeed a common practice. John Papa has a good article about them in Node. 

https://johnpapa.net/node-js-everywhere-with-environment-variables/

**Comment by macasas** [comment]
Oh, thanks for this repo and the youtube video on clean architecture. It's really useful to have a practical example of javascript to go with all the theory. I really appreciate it!  Thanks.

**Comment by Ryuno-Ki** [comment]
Hm, I've heard about this via [12factor app](https://12factor.net/config) (popular among the Java devs at work).

Regarding credentials, I always feel a bit ... uncomfortable.
I don't want to have them in source control for security reasons.
I can't control how can access environment variables outside of my app...
But keeping it in a file would allow other processes to read it also. At least I can regulate it here via Unix user/groups and perms.

`.env` are supported across different programming languages by now so my best bet.

**Comment by edwardmosan123** [comment]
> Hm, I've heard about this via [12factor app](https://12factor.net/config) (popular among the Java devs at work).
> 
> Regarding credentials, I always feel a bit ... uncomfortable.
> I don't want to have them in source control for security reasons.
> I can't control how can access environment variables outside of my app...
> But keeping it in a file would allow other processes to read it also. At least I can regulate it here via Unix user/groups and perms.
> 
> `.env` are supported across different programming languages by now so my best bet.

.env can be supported in many programming languages. so, don't worry. for more information visit [AOL gold.](http://desktopgolddownload.net/)

**Comment by arcdev1** [comment]
Fixed by #15
