### ISSUE TITLE
Works out of the box?

### ISSUE THREAD

**Issue by bullettrang** [dev-mastery/comments-api#14]
Hello Bill,

I just wanted to try and mess around with the app similar to how you did it in mastery Monday by doing a POST with a body of {
	"author":"Wayne",
	"text":"Party time",
	"postId":"cjt65art5350vy000hm1rp3s9"
}

However I only get 404 errors. Do I need to do something additional to get the routes working?

**Comment by arcdev1** [comment]
Have you installed all the pre-requisites, created accounts for Akismet and Content Moderator, and modified the .env file as per the README?

**Comment by bullettrang** [comment]
Yes, I have mongd running, 

I modified the .env file to include DM_ENV=dev
DM_COMMENTS_DB_URL=mongodb://localhost:27017
DM_COMMENTS_DB_NAME=dm_comments_api
DM_MODERATOR_API_URL=https://westus.api.cognitive.microsoft.com/contentmoderator/moderate/v1.0/ProcessText/Screen

I replaced the API URL with **westus**, the same as my registered cognitive account. 
I also added my DM_MODERATOR_API_KEY from the cognitive credentials screen.

I made an Akismet account and added my key to the  beginning of the **SPAM API url**.

I am not sure what I am missing at this point. I think my cognitive link is the issue however but I cannot see anything wrong with my url. I followed the documentation from [https://docs.microsoft.com/en-us/rest/api/cognitiveservices/contentmoderator/textmoderation/screentext](url)

**Comment by arcdev1** [comment]
@bullettrang I saw your pull requests. Did you manage to resolve the issue?

**Comment by bullettrang** [comment]
Hello Bill,

Unfortunately not, still a 404 error. I spent an hour combing through my .env file and reading Cognitive documentation but I can't seem to get pass the error.

I tried changing the DM_MODERATOR_API_URL to various formats to no avail.
I also tried adding additional headers per the example at [documentation](https://westus.dev.cognitive.microsoft.com/docs/services/57cf753a3f9b070c105bd2c1/operations/57cf753a3f9b070868a1f66f) such as Host but I still get a 404. 

I noticed in the Youtube video you had a 1 header while making the first Wayne comment. Did I need to add a header of some sort while querying the app in Postman?

**Comment by arcdev1** [comment]
You shouldn't need any special headers. Can you call the Moderator and Akismet APIs directly from Postman?

Also, dumb question, but are you sure the server is running?

**Comment by bullettrang** [comment]
hmm my terminal printout does says "listening on port 3000" so I believe so. 

Here are my screen shots of my Postman calls

![my-api-call](https://user-images.githubusercontent.com/26558593/69691884-33902180-1085-11ea-834b-f2ab2d79efb5.png)

![akismet](https://user-images.githubusercontent.com/26558593/69691891-3ee34d00-1085-11ea-885e-ee774fecfe6b.png)

![cognitive-api](https://user-images.githubusercontent.com/26558593/69691902-4c003c00-1085-11ea-9e78-552b93c06634.png)

my .env file
![image](https://user-images.githubusercontent.com/26558593/69691950-73ef9f80-1085-11ea-99c3-9b5fa16ddd5e.png)

rest of my .env file with api keys slightly removed.
![image](https://user-images.githubusercontent.com/26558593/69692017-a6999800-1085-11ea-8b89-4a277613d00a.png)

**Comment by arcdev1** [comment]
Okay ... I pulled this down from scratch and I can recreate the issue. 

Debugging now (but may have to go to bed shortly).

**Comment by bullettrang** [comment]
No worries Bill, I know you're a busy developer. I appreciate all your help and I have been religiously watching your videos until I start my first developer job on 12/2.

**Comment by arcdev1** [comment]
Okay. I figured it out. The message you are getting is because express js is unable to match the route. 

Your .env file sets `DM_API_ROOT=apiv1` but in Postman you are targeting: `http://localhost:3000/api/comments/`.

Change the address in Postman to: `http://localhost:3000/apiv1/comments/` and it should work.

**Comment by bullettrang** [comment]
Oh sorry I hard coded api into my routes since I thought using a template string was causing the issue. I already changed the routes to between api and apiv1 with no success. I tried hard coding a simple home route to see if my server was like and was able to get a response from postman.

**Comment by arcdev1** [comment]
Hmmm ... well `error: { "Not found." }` is being sent from here:

https://github.com/dev-mastery/comments-api/blob/7c93f3d498d626da8fbd1fb9407994e82fb7e97b/src/index.js#L29

This should only happen if no route matches are found.

**Comment by bullettrang** [comment]
well here is my index.js for reference ( started up project with npm run dev)

![image](https://user-images.githubusercontent.com/26558593/69693372-fed29900-1089-11ea-81e8-85c5cd6f43f8.png)

![image](https://user-images.githubusercontent.com/26558593/69693439-26296600-108a-11ea-89a3-d583f8c61583.png)

**Comment by arcdev1** [comment]
Try starting up with `npm run start` to make sure we have a clean build and a seeded database and make sure the url you are posting to matches what is defined in your .env file in the form:

`<DM_BASE_URL><DM_API_ROOT>/comments`

**Comment by Ryuno-Ki** [comment]
Regarding DNT: https://blog.revathskumar.com/2015/01/expressjs-respect-dnt-header.html should still work.

You can use netstat to check for ports is listening: `netstat -tulpen` (OTOH).

**Comment by Ryuno-Ki** [comment]
Stupid idea: could it be the trailing slash missing in the route registrations?

**Comment by bullettrang** [comment]
@Ryuno-Ki  You're a genius sir. It was the trailing slash for routes in index.js. Surprisingly my .env file doesn't register the trailing slash in my DM_BASE_URL. I tried leaving and removing the ending '/' from http://localhost:3000 and it made no difference.
