### ISSUE TITLE
Wrong import when injecting is-questionable in handleModeration

### ISSUE THREAD

**Issue by paduc** [dev-mastery/comments-api#27]
https://github.com/dev-mastery/comments-api/blob/7c93f3d498d626da8fbd1fb9407994e82fb7e97b/src/use-cases/index.js#L7

Shouldn't the import be 
```javascript
import isQuestionable from '../is-questionable'
```
?

Thank you for your awesome videos and examples btw !

**Comment by arcdev1** [comment]
Yes. Good catch. Wanna make a pull request?

**Comment by paduc** [comment]
Don’t mind if I do 😊

https://github.com/dev-mastery/comments-api/pull/28
