### ISSUE TITLE
Why dependency injection here?

### ISSUE THREAD

**Issue by lffg** [dev-mastery/comments-api#30]
https://github.com/dev-mastery/comments-api/blob/e55a2a9396798e43e7aa9254c4fb5d445e2f508e/src/controllers/get-comments.js#L1

Hey Bill, thanks for the awesome video! Just a question...

Why are you injecting an use-case in a controller, which is at a lower level compared to an use-case? Wouldn't be a source-code dependency in this case more "right"?

**Comment by arcdev1** [comment]
This is related to #8 and you are correct. It would be more in keeping with the "rules" of Clean Architecture to directly import a use-case in a controller.

**Comment by lffg** [comment]
Oh, thanks — and sorry about the duplicated issue. :D

**Comment by arcdev1** [comment]
No need to apologize. It's a good observation and a valid question. Thanks for watching the video and engaging :)
