### ISSUE TITLE
How should I include Transactions, without breaking this source code architecture? 

### ISSUE THREAD

**Issue by garganshul108** [dev-mastery/comments-api#38]
Hello,
First of all thanks for a wonderful tutorial!!

I am working on an Express-based API that uses MySQL for data persistence. I have to implement a **confirm order** functionality
- I have an already recorded order with ordered item list in my DB (like order in the pending state)
- Now on confirming order action I need to subtract each item quantity from each some super-item present in the DB record, with a check that no value turns negative (i.e. no ordered qty is more than present qty)
- If it is done for all the items under a "**transaction cover**" then I have to commit the transaction
- Else revert back to the previous state (i.e rollback)

I know how to run Mysql specific transactions and all the things, but with a lot of coupling and poor source code architecture. (If I do it that way, then DB won't be like plugin anymore)

I am not able to understand how to do this while maintaining the architecture and at what layer to implement this transaction thing, use-case/data-access, or what?
Thanks in advance

PS: also suggest to me, if it is an automation logic or business logic?

**Comment by arcdev1** [comment]
If you need transactions you probably should reach for a UnitOfWork. Here's a decent description:
https://dejanvasic.wordpress.com/2020/01/03/unit-of-work-with-node-mssql-and-typescript/

**Comment by garganshul108** [comment]
Thanks, Bill!

**Comment by garganshul108** [comment]
If you allow me, I have a request.

Please Please Please!
Make a similar API using Java Spring Boot.
