### ISSUE TITLE
Typo in src/index.js: app.put instead of app.patch

### ISSUE THREAD

**Issue by liboar** [dev-mastery/comments-api#46]
The title says it all.

https://github.com/dev-mastery/comments-api/blob/2b797727a37cb149bbb87da906b84779f8e4c97d/src/index.js#L26
https://github.com/dev-mastery/comments-api/blob/2b797727a37cb149bbb87da906b84779f8e4c97d/src/index.js#L27

**Comment by arcdev1** [comment]
Thanks for the heads up. This app does not support PUT, only PATCH, so app.patch is correct. But line 27 does look fishy and could be a copy/paste error. It's been a while since I've fired this up, so I'll need to investigate.

Thanks again.

**Comment by liboar** [comment]
I was having an related error so long, that I didn't even consider app.patch would be right. My bad!

Thank you for your API, there is so much, I can learn from.
