### ISSUE TITLE
sampledotenv needs "DM_API_ROOT"

### ISSUE THREAD

**Issue by fy2** [dev-mastery/comments-api#75]
Hi, thank you for the great work + tutorial.

I think that `DM_API_ROOT=/api` should be added to the `sampledotenv` file as it would otherwise not work currently.

**Comment by arcdev1** [comment]
Thanks for pointing this out. Would you be willing to submit a pull request?

**Comment by fy2** [comment]
Absolutely, I will do it today.

I must say this is a most enlightening piece of work, can't thank you enough for this. I am still trying to truly understand all the relationships and the layering you have created. I might have a question or two later if you don't mind :) it is extremely helpful!

**Comment by arcdev1** [comment]
Thanks and feel free to add questions as new issues. This repo is all about learning. I'll do my best to answer (although sometimes it might take a while as I tend to get busy).
